import React from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import AuthProvider from "@/providers/auth-provider";

const vazir = localFont({
    src: [
        { path: "./fonts/Vazir-Black.woff", weight: "800", style: "black" },
        { path: "./fonts/Vazir-Bold.woff", weight: "600", style: "Bold" },
        { path: "./fonts/Vazir-Regular.woff", weight: "500", style: "Regular" },
        { path: "./fonts/Vazir-Medium.woff", weight: "400", style: "Medium" },
        { path: "./fonts/Vazir-Light.woff", weight: "300", style: "Light" },
        { path: "./fonts/Vazir-Thin.woff", weight: "200", style: "Thin" },
    ],
    variable: "--font-vazir",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" dir="rtl" suppressHydrationWarning>
            <body className={`${vazir.className} antialiased bg-gray-50`}>
                <AuthProvider>
                    <Toaster />
                    <main>{children}</main>
                </AuthProvider>
            </body>
        </html>
    );
}
