import React from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/app-sidebar";
import Header from "@/components/header/header";
const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" dir="rtl" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable}  antialiased  h-screen`}>
                <Header />
                <SidebarProvider>
                    <div className="grid grid-cols-[auto,1fr] w-full">
                        <AppSidebar />
                        <main className="flex flex-col h-screen overflow-auto">
                            <SidebarTrigger className="absolute top-4" />
                            {children}
                        </main>
                    </div>
                </SidebarProvider>
            </body>
        </html>
    );
}
